apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: db1
    persistentVolumeClaim:
        claimName: db1
  containers:
  - name: postgres
    image: docker.io/postgres:14
    imagePullPolicy: Always
    volumeMounts:
    - name: db1
      mountPath: /db1
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: mysitepassword
    - name: POSTGRES_DB
      value: "mysitedb"
    - name: POSTGRES_USER
      value: "mysiteuser"
    - name: DB_PASSWORD
      value: "django" 
    - name: DB_ENGINE
      value: "postgres"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "testtest"
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi