apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: db1
    persistentVolumeClaim:
        claimName: db1
  containers:
  - name: postgres
    image: docker.io/postgres:14
    imagePullPolicy: Always
    volumeMounts:
    - name: db1
      mountPath: /var/lib/postgresql
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: "mysitepassword"
    - name: POSTGRES_DB
      value: "mysitedb"
    - name: POSTGRES_USER
      value: "mysiteuser"
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi